### PR TITLE
Allow removal of output trace

### LINKED ISSUE #4: Allow removal of stacktrace
If a test visits a lot of pages the output can _stack_ up quite dramatically. We should be able to turn this off.

### PR DESCRIPTION
**Pull request by acbramley**
Fixes #4 

Needs tests.

### CODE REVIEW

**Comment by acbramley** [comment]
Any further fixes here? The failures look unrelated?

**Comment by dpi** [comment]
Was hoping to resolve test things but hitting a time limit. Thanks!

**Comment by dpi** [comment]
will create a release in the near future

**Comment by dpi** [comment]
Fixed tests polluting ENV vars in #6.

Changes can be found in 0.2.0

**Pull request merged**
